version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running tests...
      - python -m pytest -v || true
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app.py
    - requirements.txt
    - appspec.yml
    - scripts/**/*
  discard-paths: no